// Generated by CoffeeScript 1.6.3
(function() {
  var blog;

  blog = {
    list: function(req, res) {
      return res.send('blog list');
    },
    show: function(req, res) {
      return res.send('ok');
    }
  };

}).call(this);

/*
//@ sourceMappingURL=blog.map
*/
