// Generated by CoffeeScript 1.6.3
(function() {
  var route, user;

  user = require('./user');

  route = function(app) {
    app.get('/', function(req, res) {
      return res.send('hello Nodejs with Coffee');
    });
    app.get('/login', user.toLogin);
    app.post('/login', user.login);
    return null;
  };

  module.exports = route;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
