// Generated by CoffeeScript 1.6.3
(function() {
  var router, user;

  user = require('./user');

  router = function(app) {
    app.get('/', function(req, res) {
      return res.render('index', {
        title: 'nodejs and coffee'
      });
    });
    app.get('/user', function(req, res) {
      return user.toLogin(req, res);
    });
    return app.post('/user', function(req, res) {
      return user.login(req, res);
    });
  };

  module.exports = router;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
