// Generated by CoffeeScript 1.6.3
(function() {
  var user;

  user = {
    toLogin: function(req, res) {
      return res.render('signin', {
        title: '登录'
      });
    },
    login: function(req, res) {
      var username, userpwd;
      username = req.body.userName;
      userpwd = req.body.userPwd;
      if (username === 'gordon' && userpwd === '111111') {
        return res.render('index', {
          title: "恭喜你" + username + " 登录成功"
        });
      } else {
        return res.render('signin', {
          title: "请重新登录"
        });
      }
    }
  };

  module.exports = user;

}).call(this);

/*
//@ sourceMappingURL=user.map
*/
