// Generated by CoffeeScript 1.6.3
(function() {
  var user;

  user = {
    toLogin: function(req, res) {
      res.render('login', {
        title: "登陆页面"
      });
      return null;
    },
    login: function(req, res) {
      var userName, userPwd;
      userName = req.body.username;
      userPwd = req.body.userpwd;
      console.log(userName);
      console.log(userPwd);
      res.send("登陆的用户为 " + userName + " , 密码为:" + userPwd);
      return null;
    },
    logout: function(req, res) {
      return console.log("登陆成功");
    }
  };

  module.exports = user;

}).call(this);

/*
//@ sourceMappingURL=user.map
*/
